image: openjdk:8-jdk


stages:
  - build


variables:
    DOCKER_DRIVER: overlay2


build-jar:
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - ./gradlew clean build
  after_script:
    - cat telegraff-core/build/reports/jacoco/test/html/index.html
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    paths:
      - telegraff-core/build/reports/
    expire_in: 1 week
    when: always
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches